name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'  # Игнорируем изменения только в README

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout кода
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Получаем полную историю для корректной работы версий

      # Установка Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Указываем версию Node.js (можно изменить под ваши нужды)
          cache: 'npm'

      # Установка зависимостей
      - name: Install Dependencies
        run: npm ci

      # Сборка документации
      - name: Build
        run: npm run build

      # Деплой на gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: docs.adapty.io  # Опционально: если нужен кастомный домен
          destination_dir: docs  # Соответствует baseUrl: "/docs/" в конфиге
          keep_files: false  # Очищаем старые файлы перед деплоем

    # Условие для проверки, что изменен не только README
    if: "github.event_name == 'push' && !contains(github.event.head_commit.message, 'README')"
