name: Deploy Docusaurus to GitHub Pages

permissions:
  contents: read
  pages: write
  # Добавляем разрешение на запись комментариев
  pull-requests: write  # Нужен доступ для комментирования, если это PR
  repository-projects: write  # На случай, если это связано с коммитом напрямую

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          destination_dir: docs
          keep_files: false

      - name: Add comment with docs URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = context.sha;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;
            const docsUrl = `https://${repoOwner}.github.io/${repoName}/docs/`;
            
            await github.rest.repos.createCommitComment({
              owner: repoOwner,
              repo: repoName,
              commit_sha: commitSha,
              body: `Documentation deployed successfully! Check it out here: ${docsUrl}`
            });
